name: CI Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:

  secret-scan:
    name: Scan for secrets
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    name: Run Backend Tests
    runs-on: ubuntu-latest
    needs: secret-scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: pip install -r backend/requirements.txt

      - name: Fix bcrypt version
        run: pip install bcrypt==4.0.1

      - name: Run Bandit Security scan
        run: |
          pip install Bandit
          bandit -r backend/ -ll

      - name: Run tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
        run: pytest backend/test_main.py -v
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build backend image
        run: docker build -t auth-backend ./backend

      - name: Build frontend image
        run: docker build -t auth-frontend ./frontend

  container-scan:
    name: Scan Container and Dependencies
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build backend image for scanning
        run: docker build -t auth-backend ./backend

      - name: Build Frontend image for scanning
        run: docker build -t auth-frontend ./frontend

      - name: Scan backend image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: auth-backend
          format: table
          severity: CRITICAL,HIGH
          exit-code: '0'

      - name: Scan Frontend image with Trivy
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: auth-frontend
          format: table
          severity: CRITICAL,HIGH
          exit-code: '0'

      - name: Install Python dependencies for Snyk
        run: pip install -r backend/requirements.txt

      - name: Fix bcrypt for Snyk
        run: pip install bcrypt==4.0.1

      - name: Scan dependencies with Snyk
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --file=backend/requirements.txt


        
